core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    # Authentication
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout'),

    # Users management
    path('new/', views.users_new, name="new"),
    path('list/', views.users_list, name="list")
]

v2cschool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

from school.models import School

class User(AbstractUser):
    CHOICES = [
        ('girl', 'Fille'),
        ('boy', 'Garçon')
    ]

    birth_date = models.DateField(blank=True, null=True)
    town = models.CharField(max_length=50, blank=True, null=True)
    neighborhood = models.CharField(max_length=50, blank=True, null=True)
    sex = models.CharField(max_length=50, choices=CHOICES, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    school = models.ForeignKey(School, on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Profile(models.Model):
    CHOICES = [
        ('admin', 'Administrateur'),
        ('teacher', 'Enseignant')
    ]
    
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    role = models.CharField(max_length=50, choices=CHOICES, default='admin')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.role

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password

from .models import User, Profile
from school.models import School

# AUTHENTICATION
def signin(request):
    if request.user.is_authenticated:
        # If user is already authenticated, redirect them to dashboard
        return redirect('core:index')
    
    if request.method == 'POST':
        # Retrieve data from the form
        username = request.POST['username']
        password = request.POST['password']
        
        # Verify user's credentials and returns a User object if the credentials are valid for a backend
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            # Authentication successful, log the user in. This line creates a sessionId for the user.
            login(request, user)
            return redirect('core:index')  # Redirect to dashboard page after successful login
        else:
            # Authentication failed, display error message
            error_message = "Invalid username or password. Please try again."
            return render(request, 'users/auth/signin.html', {'error_message': error_message})

    return render(request, 'users/auth/signin.html', {})


def signup(request):
    if request.user.is_authenticated:
        # If user is already authenticated, redirect them to dashboard
        return redirect('core:index')
    
    if request.method == 'POST':
        # Retrieve data from the form
        school_name = request.POST.get('school_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        
        # Create school
        school_created = School.objects.create(name=school_name) 

        # Create user (superuser)
        user = User.objects.create_superuser(username=username, email=email, password=password, school=school_created)  

        # Create user's profile  
        Profile.objects.create(user=user)
        
        # Redirect to login page
        return redirect('users:signin')

    return render(request, 'users/auth/signup.html', {})


@login_required
def logout_view(request):
    logout(request)
    return redirect('users:signin')


@login_required
def users_new(request):
    if request.method == 'POST':
        # Retrieve data from the form
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        role = request.POST.get('role')
        birth_date = request.POST.get('birth_date')
        town = request.POST.get('town')
        neighborhood = request.POST.get('neighborhood')
        sex = request.POST.get('sex')
        phone = request.POST.get('phone')
        password = request.POST.get('password')
        password_confirm = request.POST.get('password_confirm')
        # photo = request.POST.get('photo')

        # Verify that required fields are set
        if not first_name or not email or not role or not birth_date or not password or not password_confirm:
            # Rediriger vers le formulaire avec un message d'erreur
            return render(request, 'users/users_new.html', {'error_message': 'Veuillez remplir tous les champs obligatoires'})

        # Verify that passwords match
        if password != password_confirm:
            # Les mots de passe ne correspondent pas, rediriger vers le formulaire avec un message d'erreur
            return render(request, 'users/users_new.html', {'error_message': 'Les mots de passe ne correspondent pas'})


        # Create user
        user = User.objects.create(
            username = first_name,
            first_name = first_name,
            last_name = last_name,
            email = email,
            birth_date = birth_date,
            town = town,
            neighborhood = neighborhood,
            sex = sex,
            phone = phone,
            password = make_password(password),
            school = request.user.school
        ) 

        # Create user's profile
        Profile.objects.create(
            role=role,
            user=user
        )

        return redirect('users:list')


    return render(request, 'users/users_new.html', {})

@login_required
def users_list(request):
    users = User.objects.filter(school=request.user.school).exclude(id=request.user.id)
    return render(request, 'users/users_list.html', {'users': users})

users/templates/users/login.html
{% extends '_base.html' %}

<!-- Static Files Loader -->
{% load static %}

<!-- Title page -->
{% block title %}Se connecter{% endblock %}

<!-- CSS -->
{% block custom_css %}
<link rel="stylesheet" href="{% static 'users/css/login.css' %}" />
{% endblock %}

<!-- CONTENT -->
{% block content %}
<div class="login__container">
  <div class="login__back">
    <a href="#"
      ><svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        class="bi bi-arrow-bar-left"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5M10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5"
        />
      </svg>
      school-lab</a
    >
  </div>
  <div class="login__wrapper">
    <div class="login__cta">
      <h1 class="login__heading">Se connecter à l'application</h1>
      <p class="login__sub-heading">
        ou <a href="{% url 'users:register' %}">ouvrir un compte</a>
      </p>
    </div>
    <form action="#" class="login__form">
      <div class="login__form__group">
        <label for="#">Nom d'utilisateur (ou Adresse Email)</label>
        <input type="text" />
      </div>
      <div class="login__form__group">
        <label for="#">Mot de passe</label>
        <input type="password" />
      </div>
      <button class="btn primary">Se connecter</button>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends '_base.html' %}

<!-- Static Files Loader -->
{% load static %}

<!-- Title page -->
{% block title %}Creer votre compte{% endblock %}

<!-- CSS -->
{% block custom_css %}
<link rel="stylesheet" href="{% static 'users/css/register.css' %}" />
{% endblock %}

<!-- CONTENT -->
{% block content %}
<div class="register__container">
  <div class="register__wrapper">
    <img class="logo-img" src="{% static 'images/png/logo.png' %}" alt="logo" />
    <h1 class="register__heading">Créez votre compte</h1>
    <p class="register__info">
      Vous avez déjà un compte?
      <a href="{% url 'users:login' %}">Se connecter</a>
    </p>
    <form action="#" class="register__form">
      <div class="form__group">
        <label for="#">Nom Etablissement</label>
        <div class="form__item">
          <input type="text" />
        </div>
      </div>
      <div class="form__group">
        <label for="#">Nom utilisateur</label>
        <div class="form__item">
          <input type="text" />
        </div>
      </div>
      <div class="form__group">
        <label for="#">Adresse Email</label>
        <div class="form__item">
          <input type="email" />
        </div>
      </div>
      <div class="form__group">
        <label for="#">Mot de passe</label>
        <div class="form__item">
          <input type="password" />
        </div>
      </div>
      <div>
        <button class="btn primary">Créer votre compte</button>
        <p class="term-of-service">
          En cliquant sur ce bouton, vous acceptez les
          <a href="#">conditions générales</a> et la
          <a href="#">politique de confidentialité</a>.
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/signin.html
{% extends '_base.html' %}

<!-- Static Files Loader -->
{% load static %}

<!-- Title page -->
{% block title %}Se connecter{% endblock %}

<!-- CSS -->
{% block custom_css %}
<link rel="stylesheet" href="{% static 'users/css/login.css' %}" />
{% endblock %}

<!-- CONTENT -->
{% block content %}
<div class="login__container">
  <div class="login__back">
    <a href="#"
      ><svg
        xmlns="http://www.w3.org/2000/svg"
        width="16"
        height="16"
        fill="currentColor"
        class="bi bi-arrow-bar-left"
        viewBox="0 0 16 16"
      >
        <path
          fill-rule="evenodd"
          d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5M10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5"
        />
      </svg>
      school-lab</a
    >
  </div>
  <div class="login__wrapper">
    <div class="login__cta">
      <h1 class="login__heading">Se connecter à l'application</h1>
      <p class="login__sub-heading">
        ou <a href="{% url 'users:signup' %}">ouvrir un compte</a>
      </p>
    </div>
    <form class="login__form" method="post">
      {% csrf_token %}
      <div class="login__form__group">
        <label for="#">Nom d'utilisateur</label>
        <input name="username" type="text" />
      </div>
      <div class="login__form__group">
        <label for="#">Mot de passe</label>
        <input name="password" type="password" />
      </div>
      <button type="submit" class="btn primary">Se connecter</button>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends '_base.html' %}

<!-- Static Files Loader -->
{% load static %}

<!-- Title page -->
{% block title %}Creer votre compte{% endblock %}

<!-- CSS -->
{% block custom_css %}
<link rel="stylesheet" href="{% static 'users/css/register.css' %}" />
{% endblock %}

<!-- CONTENT -->
{% block content %}
<div class="register__container">
  <div class="register__wrapper">
    <img class="logo-img" src="{% static 'images/png/logo.png' %}" alt="logo" />
    <h1 class="register__heading">Créez votre compte</h1>
    <p class="register__info">
      Vous avez déjà un compte?
      <a href="{% url 'users:signin' %}">Se connecter</a>
    </p>
    <form class="register__form" method="post">
      {% csrf_token %}
      <div class="form__group">
        <label for="#">Nom Etablissement</label>
        <div class="form__item">
          <input name="school_name" type="text" />
        </div>
      </div>
      <div class="form__group">
        <label for="#">Nom utilisateur</label>
        <div class="form__item">
          <input name="username" type="text" />
        </div>
      </div>
      <div class="form__group">
        <label for="#">Adresse Email</label>
        <div class="form__item">
          <input name="email" type="email" />
        </div>
      </div>
      <div class="form__group">
        <label for="#">Mot de passe</label>
        <div class="form__item">
          <input name="password" type="password" />
        </div>
      </div>
      <div>
        <button type="submit" class="btn primary">Créer votre compte</button>
        <p class="term-of-service">
          En cliquant sur ce bouton, vous acceptez les
          <a href="#">conditions générales</a> et la
          <a href="#">politique de confidentialité</a>.
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %}

users/templates/users/users_new.html
{% extends 'core/_base.html' %}

<!-- Title -->
{% block title %} Nouveau utilisateur {% endblock %}

<!-- Content -->
{% block core_content %}
<!-- error message -->
{{error_message}}

<form method="post">
  {% csrf_token %}
  <header>
    <div class="header__navigation m-r-30 border-b">
      <a href="{% url 'users:list' %}" class="header__backlink">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="16"
          height="16"
          fill="currentColor"
          class="bi bi-arrow-left"
          viewBox="0 0 16 16"
        >
          <path
            fill-rule="evenodd"
            d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"
          />
        </svg>
        Liste des utilisateurs
      </a>
      <div class="header__wrapper">
        <h1 class="header__title">Nouveau utilisateur</h1>
        <div class="header__actions">
          <button class="btn secondary">Enregistrer & ajouter un autre</button>
          <button type="submit" class="btn primary">Enregistrer</button>
        </div>
      </div>
    </div>
  </header>

  <div class="content w-40">
    <div class="content__wrapper">
      <div class="box">
        <div class="box__wrapper">
          <div class="box__header">
            <h2 class="box__title">Créer un nouveau utilisateur</h2>
            <span class="box__info">* Information requise</span>
          </div>
          <div class="box__content">
            <div class="form__row">
              <div class="form__group">
                <label for="first_name">Nom *</label>
                <div class="form__item">
                  <input name="first_name" type="text" id="first_name" />
                </div>
              </div>
              <div class="form__group">
                <label for="last_name">Prenom</label>
                <div class="form__item">
                  <input name="last_name" type="text" id="last_name" />
                </div>
              </div>
            </div>
            <div class="form__row">
              <div class="form__group">
                <label for="email">Email *</label>
                <div class="form__item">
                  <input name="email" type="text" for="email" required />
                </div>
              </div>
              <div class="form__group">
                <label for="role">Role *</label>
                <div class="form__item">
                  <select name="role" id="role" required>
                    <option value="teacher">Enseignant</option>
                    <option value="provisor">Proviseur</option>
                    <option value="admin">Administrateur</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="box">
        <div class="box__wrapper">
          <div class="box__header">
            <h2 class="box__title">Informations supplementaires</h2>
          </div>
          <div class="box__content">
            <div class="form__row">
              <div class="form__group">
                <label for="birth_date">Date naissance</label>
                <div class="form__item">
                  <input
                    name="birth_date"
                    type="date"
                    id="birth_date"
                    required
                  />
                </div>
              </div>
              <div class="form__group">
                <label for="town">Ville</label>
                <div class="form__item">
                  <input name="town" type="text" id="town" />
                </div>
              </div>
            </div>
            <div class="form__row">
              <div class="form__group">
                <label for="neighborhood">Quartier</label>
                <div class="form__item">
                  <input name="neighborhood" type="text" id="neighborhood" />
                </div>
              </div>
              <div class="form__group">
                <label for="sex">Sexe</label>
                <div class="form__item">
                  <select name="sex" id="sex">
                    <option value="masculin">Masculin</option>
                    <option value="feminin">Feminin</option>
                  </select>
                </div>
              </div>
            </div>
            <div class="form__row">
              <div class="form__group">
                <label for="phone">Telephone</label>
                <div class="form__item">
                  <input name="phone" type="text" id="phone" />
                </div>
              </div>
              {% comment %}
              <div class="form__group">
                <label for="image">Photo *</label>
                <div class="form__item">
                  <input name="image" type="file" id="image" />
                </div>
              </div>
              {% endcomment %}
            </div>
          </div>
        </div>
      </div>

      <div class="box">
        <div class="box__wrapper">
          <div class="box__header">
            <h2 class="box__title">Mot de passe</h2>
          </div>
          <div class="box__content">
            <div class="form__row">
              <div class="form__group">
                <label for="password">Mot de passe *</label>
                <div class="form__item">
                  <input
                    name="password"
                    type="password"
                    id="password"
                    required
                  />
                </div>
              </div>
            </div>
            <div class="form__row">
              <div class="form__group">
                <label for="password_confirm">Confirmer Mot de passe *</label>
                <div class="form__item">
                  <input
                    name="password_confirm"
                    type="password"
                    id="password_confirm"
                    required
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}